# Generated by Django 4.2.6 on 2023-10-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userq',
            fields=[
                ('id', models.CharField(default='yRsb2_CdJUibXXCD', editable=False, max_length=16, primary_key=True, serialize=False)),
            ],
        ),
    ]
