# Generated by Django 4.2.6 on 2023-10-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_user_delete_userq'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='operator', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='2xfrcxgl9kEWOXSv', editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
