# Generated by Django 4.2.6 on 2023-10-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_user_role_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='5OxHPoHPT7VnPEUS', editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
