# Generated by Django 4.2.6 on 2023-10-14 09:40

import auth_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=auth_user.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
