# Generated by Django 4.2.6 on 2023-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_hp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
